### ISSUE TITLE
v2 breaks references to nested objects

### ISSUE THREAD

**Issue by NightTsarina** [imranbarbhuiya/typedoc-plugin-external-link#116]
### Issue description

Hi,

Today I updated the typescript and typedoc dependencies in a project to take advantage of new features, but found a regression in the new version of this plugin.

Before, getURL would get the full symbol path as a string, but now it only gets the first element, so `{@link}`s will render with incorrect link *and* caption.

### Code sample

My `externalConfig.js`:

```javascript
const packageNames = ['devtools-protocol'];

function getURL(packageName, type) {
    console.log(`getURL(${packageName}, ${type})`);
    const error = () => {
        console.error(`getURL failed for ${packageName}/${type})`);
        return undefined;
    };
    if (packageName === 'devtools-protocol') {
        const baseURL = 'https://vanilla.aslushnikov.com/';
        const prefix = 'Protocol';
        if (!type || type === prefix) {
            return baseURL;
        } else if (type.startsWith(prefix + '.')) {
            const cleanType = type.slice(prefix.length + 1);
            return `${baseURL}?${cleanType}`;
        } else {
            return error();
        }
    } else {
        return error();
    }
}

module.exports = { packageNames, getURL };
```

JSDoc:

```javascript
    /**
     * Retrieve all browser cookies.
     *
     * @see {@link devtools-protocol!Protocol.Storage.getCookies |
     *   Storage.getCookies}
     * @returns {Promise<import('devtools-protocol').Protocol.Network.Cookie[]>}
     *   Array of cookie objects.
     */
```

In version 1.0.3, the `console.log` line tells me the function is called as `getURL('devtools-protocol', 'Protocol.Network.Cookie')` and the links are rendered as:

```html
<a href="https://vanilla.aslushnikov.com/?Network.Cookie" class="tsd-signature-type external" target="_blank">Cookie</a>
<!-- ... -->
<h3>See</h3><p><a href="https://vanilla.aslushnikov.com/?Storage.getCookies">Storage.getCookies</a></p>
</div>
```

Whereas in version 2.0.0, the function is called as `getURL('devtools-protocol', 'Protocol')`, and the links are rendered as:

```html
<a href="https://vanilla.aslushnikov.com/" class="tsd-signature-type external" target="_blank">Cookie</a>
<!-- ... -->
<h4>See</h4><p><a href="https://vanilla.aslushnikov.com/">Storage.getCookies</a></p>
```

### Package version

2.0.0

### Node.js version

node 18.13.0, typescript 5.0.4

### Operating system

Linux

**Comment by imranbarbhuiya** [comment]
If I give all the symbols as multiple parameters of `getURL` function to not break existing behavior, will it solve your issue?
```ts
export type getURL = (packageName: string, ...types: (string | undefined)[]) => string | undefined;

```
like this

**Comment by imranbarbhuiya** [comment]
released a fix using the above mentioned type, https://github.com/imranbarbhuiya/typedoc-plugin-external-link/releases/tag/v2.1.0 check if it works for u

now your code will be
```ts
const packageNames = ['devtools-protocol'];

- function getURL(packageName, type) {
+ function getURL(packageName, ...types) {
+ const type = types.join('.');
    console.log(`getURL(${packageName}, ${type})`);
    const error = () => {
        console.error(`getURL failed for ${packageName}/${type})`);
        return undefined;
    };
    if (packageName === 'devtools-protocol') {
        const baseURL = 'https://vanilla.aslushnikov.com/';
        const prefix = 'Protocol';
        if (!type || type === prefix) {
            return baseURL;
        } else if (type.startsWith(prefix + '.')) {
            const cleanType = type.slice(prefix.length + 1);
            return `${baseURL}?${cleanType}`;
        } else {
            return error();
        }
    } else {
        return error();
    }
}

module.exports = { packageNames, getURL };
```
or better check types length and index

**Comment by imranbarbhuiya** [comment]
Closing it as a fix was implemented. Reopen if r still having issues

**Comment by NightTsarina** [comment]
Thanks for the quick fix! Sorry I did not reply before, I was away for the weekend..

One issue I see with your fix is that I think the typing has a mistake, as `ref.symbolReference.path` is an array of strings (see https://typedoc.org/api/interfaces/SymbolReference.html). So this will be more precise and simplify user's code:
```diff
-export type getURL = (packageName: string, ...types: (string | undefined)[]) => string | undefined;
+export type getURL = (packageName: string, ...types: string[]) => string | undefined;
```

**Comment by imranbarbhuiya** [comment]
sorry for the late reply. I intentionally changed it because if I use `string` only, all the arguments u type in `getURL` fn will show `string` which is incorrect
