### ISSUE TITLE
getURL never called for package with organization scope

### ISSUE THREAD

**Issue by mrfigg** [imranbarbhuiya/typedoc-plugin-external-link#263]
### Issue description

As the title says, getURL never gets called for a package with an organization scope in the name. Code sample should be pretty self explanatory.

### Code sample

externalConfig.js
```ts
const packageNames = ['@elgato-stream-deck/node', 'eventemitter3']

/**
 * @type {import('typedoc-plugin-external-link').getURL}
 */
function getURL(packageName, ...types) {
  console.log(packageName, types)

  return `https://example.com/${packageName}/${types.join('/')}`
}

module.exports = { packageNames, getURL }
```

src/index.ts
```ts
import { StreamDeck } from '@elgato-stream-deck/node'
import EventEmitter from 'eventemitter3'

export interface Options {
  streamDeck?: StreamDeck
  eventEmitter?: EventEmitter
}
```

### Package version

2.1.2

### Node.js version

20.11.1

### Operating system

Windows 10

**Comment by mrfigg** [comment]
Ahh, this issue can probably be ignored. `@elgato-stream-deck/node` imports `StreamDeck` from `@elgato-stream-deck/core` and typescript/typedoc uses the definition location as the module source, not the import location as I assumed. When I change the example above to use `@elgato-stream-deck/core` it works.

**Comment by imranbarbhuiya** [comment]
I'll close this issue then since this plugin doesn't handle how imports are resolved
